# Book settings
title: "DRAFT: Quality Assurance of Code for Analysis and Research"
author: ""
email: gsshelp@statistics.gov.uk
logo: "./_static/qa_of_code_favicon.png"

repository:
  url: https://github.com/best-practice-and-impact/qa-of-code-guidance

html:
  favicon: "./_static/qa_of_code_favicon.png"
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_footer: "<p>Best Practice & Impact division, Office for National Statistics</p><p>This document is very young, please help use to make it grow by providing any feedback by <a href='mailto:gsshelp@statistics.gov.uk'>email</a> or via the <a href='https://github.com/best-practice-and-impact/qa-of-code-guidance'>GitHub repository</a>."
  extra_navbar: "<p>Book version 2020.3</><a href='https://gss.civilservice.gov.uk/' target='_blank'><img src='./_static/GSS_logo.jpg' alt='The Government Statistical Service logo' style='width:100%'></a>"

sphinx:
  extra_extensions:
    - sphinx_tabs.tabs
    - sphinx.ext.todo
  config:
    todo_include_todos: true
    language: en
    html_show_copyright: false

latex:
  latex_documents:
    targetname: book.tex
