# Book settings
title: "Quality Assurance of Code for Analysis and Research"
author: ""
email: gsshelp@statistics.gov.uk
logo: "./_static/duck_book_logo.svg"

repository:
  url: https://github.com/best-practice-and-impact/qa-of-code-guidance
  path_to_book: book

html:
  home_page_in_navbar: false
  favicon: "./_static/favicon.ico"
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  extra_footer: "<p>Analysis Function reproducible analytical pipelines (RAP) support</p><p>This is a living document, please help use to make it grow by providing any feedback <a href='mailto:Analysis.Function@ons.gov.uk'>by email</a> or via the <a href='https://github.com/best-practice-and-impact/qa-of-code-guidance'>GitHub repository</a>."
  extra_navbar: "<p>Book version 2022.3</p><a href='https://www.gov.uk/government/organisations/government-analysis-function' target='_blank'><img src='./_static/af_logo.png' alt='The Government Analysis Function logo' style='width:50%;'></a>"

sphinx:
  extra_extensions:
    - sphinx_tabs.tabs
    - sphinx.ext.todo
  config:
    todo_include_todos: true
    language: en
    html_show_copyright: false

latex:
  latex_documents:
    targetname: book.tex
